chore: expanded test runner and tests
view more details: https://github.com/DragonRidersUnite/dragon_test

diff --git a/run_tests b/run_tests
--- a/run_tests
+++ b/run_tests
@@ -1,2 +1,10 @@
 #!/usr/bin/env sh
-../dragonruby . --eval app/tests.rb --no-tick
+set -e
+rm -f test-failures.txt
+if ! ../dragonruby . --eval app/tests.rb  --no-tick --exit-on-fail; then
+	echo "🙀 tests failed!"
+	cat test-failures.txt
+	exit 1
+else
+	echo "🪩 tests passed!"
+fi
